# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import two_pc_pb2 as two__pc__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in two_pc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VotePhaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/twopc.VotePhase/RequestVote',
                request_serializer=two__pc__pb2.Transaction.SerializeToString,
                response_deserializer=two__pc__pb2.VoteReply.FromString,
                _registered_method=True)


class VotePhaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VotePhaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=two__pc__pb2.Transaction.FromString,
                    response_serializer=two__pc__pb2.VoteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.VotePhase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.VotePhase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VotePhase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.VotePhase/RequestVote',
            two__pc__pb2.Transaction.SerializeToString,
            two__pc__pb2.VoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecisionPhaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GlobalDecision = channel.unary_unary(
                '/twopc.DecisionPhase/GlobalDecision',
                request_serializer=two__pc__pb2.Decision.SerializeToString,
                response_deserializer=two__pc__pb2.Ack.FromString,
                _registered_method=True)
        self.RecordPrepared = channel.unary_unary(
                '/twopc.DecisionPhase/RecordPrepared',
                request_serializer=two__pc__pb2.PreparedState.SerializeToString,
                response_deserializer=two__pc__pb2.Ack.FromString,
                _registered_method=True)


class DecisionPhaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GlobalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPrepared(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionPhaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=two__pc__pb2.Decision.FromString,
                    response_serializer=two__pc__pb2.Ack.SerializeToString,
            ),
            'RecordPrepared': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPrepared,
                    request_deserializer=two__pc__pb2.PreparedState.FromString,
                    response_serializer=two__pc__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.DecisionPhase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.DecisionPhase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionPhase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.DecisionPhase/GlobalDecision',
            two__pc__pb2.Decision.SerializeToString,
            two__pc__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordPrepared(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.DecisionPhase/RecordPrepared',
            two__pc__pb2.PreparedState.SerializeToString,
            two__pc__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Begin = channel.unary_unary(
                '/twopc.CoordinatorControl/Begin',
                request_serializer=two__pc__pb2.BeginRequest.SerializeToString,
                response_deserializer=two__pc__pb2.Decision.FromString,
                _registered_method=True)


class CoordinatorControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Begin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Begin': grpc.unary_unary_rpc_method_handler(
                    servicer.Begin,
                    request_deserializer=two__pc__pb2.BeginRequest.FromString,
                    response_serializer=two__pc__pb2.Decision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.CoordinatorControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.CoordinatorControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Begin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.CoordinatorControl/Begin',
            two__pc__pb2.BeginRequest.SerializeToString,
            two__pc__pb2.Decision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
