# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: two_pc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'two_pc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctwo_pc.proto\x12\x05twopc\"P\n\x0bTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t\"<\n\tVoteReply\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\"J\n\x08\x44\x65\x63ision\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\x08\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t\"9\n\rPreparedState\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x10\n\x08prepared\x18\x02 \x01(\x08\"\'\n\x03\x41\x63k\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"R\n\x0c\x42\x65ginRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x17\n\x0fparticipant_ids\x18\x03 \x03(\t2@\n\tVotePhase\x12\x33\n\x0bRequestVote\x12\x12.twopc.Transaction\x1a\x10.twopc.VoteReply2r\n\rDecisionPhase\x12-\n\x0eGlobalDecision\x12\x0f.twopc.Decision\x1a\n.twopc.Ack\x12\x32\n\x0eRecordPrepared\x12\x14.twopc.PreparedState\x1a\n.twopc.Ack2C\n\x12\x43oordinatorControl\x12-\n\x05\x42\x65gin\x12\x13.twopc.BeginRequest\x1a\x0f.twopc.Decisionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_pc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=23
  _globals['_TRANSACTION']._serialized_end=103
  _globals['_VOTEREPLY']._serialized_start=105
  _globals['_VOTEREPLY']._serialized_end=165
  _globals['_DECISION']._serialized_start=167
  _globals['_DECISION']._serialized_end=241
  _globals['_PREPAREDSTATE']._serialized_start=243
  _globals['_PREPAREDSTATE']._serialized_end=300
  _globals['_ACK']._serialized_start=302
  _globals['_ACK']._serialized_end=341
  _globals['_BEGINREQUEST']._serialized_start=343
  _globals['_BEGINREQUEST']._serialized_end=425
  _globals['_VOTEPHASE']._serialized_start=427
  _globals['_VOTEPHASE']._serialized_end=491
  _globals['_DECISIONPHASE']._serialized_start=493
  _globals['_DECISIONPHASE']._serialized_end=607
  _globals['_COORDINATORCONTROL']._serialized_start=609
  _globals['_COORDINATORCONTROL']._serialized_end=676
# @@protoc_insertion_point(module_scope)
