# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"`\n\x0bVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"A\n\tVoteReply\x12\x10\n\x08voter_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x03 \x01(\x08\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\r\n\x05index\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"n\n\x14\x41ppendEntriesRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\x05\"H\n\x12\x41ppendEntriesReply\x12\x13\n\x0b\x66ollower_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07success\x18\x03 \x01(\x08\" \n\rClientCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"X\n\x0b\x43lientReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ommit_index\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t2\x89\x01\n\rRaftConsensus\x12\x31\n\x0bRequestVote\x12\x11.raft.VoteRequest\x1a\x0f.raft.VoteReply\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply2E\n\nRaftClient\x12\x37\n\rClientRequest\x12\x13.raft.ClientCommand\x1a\x11.raft.ClientReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=116
  _globals['_VOTEREPLY']._serialized_start=118
  _globals['_VOTEREPLY']._serialized_end=183
  _globals['_LOGENTRY']._serialized_start=185
  _globals['_LOGENTRY']._serialized_end=241
  _globals['_APPENDENTRIESREQUEST']._serialized_start=243
  _globals['_APPENDENTRIESREQUEST']._serialized_end=353
  _globals['_APPENDENTRIESREPLY']._serialized_start=355
  _globals['_APPENDENTRIESREPLY']._serialized_end=427
  _globals['_CLIENTCOMMAND']._serialized_start=429
  _globals['_CLIENTCOMMAND']._serialized_end=461
  _globals['_CLIENTREPLY']._serialized_start=463
  _globals['_CLIENTREPLY']._serialized_end=551
  _globals['_RAFTCONSENSUS']._serialized_start=554
  _globals['_RAFTCONSENSUS']._serialized_end=691
  _globals['_RAFTCLIENT']._serialized_start=693
  _globals['_RAFTCLIENT']._serialized_end=762
# @@protoc_insertion_point(module_scope)
